### ISSUE TITLE
Failed to run simple scenario

### ISSUE THREAD

**Issue by rozhok** [shoreditch-ops/artillery#111]
Versions:
```
$ node -v
v5.4.1

$ npm -v
3.5.3

$ artillery -V
1.5.0-4
```
Scenario:
```json
{
  "config": {
    "target": "http://our.cool.service",
    "defaults": {
      "headers": [
        {
          "Accept": "application/vnd.corp-v1+json",
          "Content-Type": "application/vnd.corp-v1+json"
        }
      ]
    },
    "phases": [
      {
        "duration": 60,
        "arrivalRate": 5
      },
      {
        "duration": 120,
        "arrivalRate": 5,
        "rampTo": 50
      },
      {
        "duration": 600,
        "arrivalRate": 50
      }
    ]
  },
  "scenarios": [
    {
      "name": "Register user",
      "flow": [
        {
          "get": {
            "url": "/home"
          }
        },
        {
          "think": 5
        }
      ]
    }
  ]
}
```
Running
```
$ artillery run hit_and_run2.json
```
Got
```
Log file: artillery_report_20160605_231290.json
Phase 0 started - duration: 60s
 -/Users/rozhkov/.node/lib/node_modules/artillery/node_modules/artillery-core/lib/engine_http.js:311
    result[k.toLowerCase()] = v;
             ^

TypeError: k.toLowerCase is not a function
    at /Users/rozhkov/.node/lib/node_modules/artillery/node_modules/artillery-core/lib/engine_http.js:311:14
    at /Users/rozhkov/.node/lib/node_modules/artillery/node_modules/artillery-core/node_modules/lodash/index.js:10033:16
    at arrayEach (/Users/rozhkov/.node/lib/node_modules/artillery/node_modules/artillery-core/node_modules/lodash/index.js:1289:13)
    at Function.transform (/Users/rozhkov/.node/lib/node_modules/artillery/node_modules/artillery-core/node_modules/lodash/index.js:10032:39)
    at lowcaseKeys (/Users/rozhkov/.node/lib/node_modules/artillery/node_modules/artillery-core/lib/engine_http.js:310:12)
    at f (/Users/rozhkov/.node/lib/node_modules/artillery/node_modules/artillery-core/lib/engine_http.js:75:26)
    at fn (/Users/rozhkov/.node/lib/node_modules/artillery/node_modules/async/lib/async.js:746:34)
    at /Users/rozhkov/.node/lib/node_modules/artillery/node_modules/async/lib/async.js:1213:16
    at /Users/rozhkov/.node/lib/node_modules/artillery/node_modules/async/lib/async.js:166:37
    at /Users/rozhkov/.node/lib/node_modules/artillery/node_modules/async/lib/async.js:706:43
```

**Comment by hassy** [comment]
`headers` should've been an object, not an array - resolved on Gitter :)
