### ISSUE TITLE
Crash with ETIMEOUT and ESOCKETTIMEDOUT

### ISSUE THREAD

**Issue by neslinesli93** [shoreditch-ops/artillery#113]
I'm doing some tests with a low end VPS (1GB ram, 1 cpu core) as a client, and with a 4GB, 2 cpu as a server. With this configuration artillery crashes a little bit after starting Phase 2:
```
"phases": [
            { "duration": 10, "arrivalRate": 100 },
            { "duration": 30, "arrivalRate": 100, "rampTo": 500 },
            { "duration": 600, "arrivalRate": 500, "rampTo": 5000 },
            { "duration": 600, "arrivalRate": 5000, "rampTo": 10000 }
        ]
```

What is the issue here? Artillery suddenly stops with a `/Killed` message.

**Update**
Sometimes I am faced with this stack trace
```
Phase 1 started - duration: 30s
 |/usr/lib/node_modules/artillery/node_modules/artillery-core/lib/engine_http.js:292
        context._agent.destroy();
               ^

TypeError: Cannot read property '_agent' of undefined
    at scenarioWaterfallCb (/usr/lib/node_modules/artillery/node_modules/artillery-core/lib/engine_http.js:292:16)
    at /usr/lib/node_modules/artillery/node_modules/async/lib/async.js:52:16
    at /usr/lib/node_modules/artillery/node_modules/async/lib/async.js:1209:30
    at /usr/lib/node_modules/artillery/node_modules/artillery-core/lib/engine_util.js:55:16
    at /usr/lib/node_modules/artillery/node_modules/async/lib/async.js:785:21
    at /usr/lib/node_modules/artillery/node_modules/async/lib/async.js:167:37
    at /usr/lib/node_modules/artillery/node_modules/artillery-core/lib/engine_util.js:51:18
    at /usr/lib/node_modules/artillery/node_modules/async/lib/async.js:52:16
    at /usr/lib/node_modules/artillery/node_modules/async/lib/async.js:696:30
    at /usr/lib/node_modules/artillery/node_modules/async/lib/async.js:167:37
```

**Comment by hassy** [comment]
`/Killed` is coming from the OOM killer I presume, i.e. the OS runs out of RAM and starts killing processes.

The arrival rates are way too high too - an arrival rate of 500 means 500 new TCP connections *per second*. That's really expensive on system resources and you will run out of file descriptors on the server very very quickly too.

**Comment by hassy** [comment]
The exception is a valid bug though (but one that would only manifest under conditions like in this case).
