### ISSUE TITLE
Cannot read property 'step' of undefined in socket.io scenario

### ISSUE THREAD

**Issue by carasel** [shoreditch-ops/artillery#140]
I am trying to run the following test:

```
{
  "config": {
    "target": "localhost:3000",
    "phases": [
      {"duration": 20, "arrivalRate": 1}
    ]
  },
  "scenarios": [
    {
      "engine" : "socketio",
      "flow": [
        {"emit": {
          "channel" : "echo",
          "data" : "hello"
         }
        }
      ]
    }
  ]
}
```

This is causing the following error:

```
//Users/steph/.nvm/versions/node/v5.5.0/lib/node_modules/artillery/node_modules/artillery-core/lib/runner.js:281
        return engine.step(rs, scenarioEvents);
                     ^

TypeError: Cannot read property 'step' of undefined
    at /Users/steph/.nvm/versions/node/v5.5.0/lib/node_modules/artillery/node_modules/artillery-core/lib/runner.js:281:22
    at arrayMap (/Users/steph/.nvm/versions/node/v5.5.0/lib/node_modules/artillery/node_modules/artillery-core/node_modules/lodash/index.js:1406:25)
    at Function.map (/Users/steph/.nvm/versions/node/v5.5.0/lib/node_modules/artillery/node_modules/artillery-core/node_modules/lodash/index.js:6710:14)
    at /Users/steph/.nvm/versions/node/v5.5.0/lib/node_modules/artillery/node_modules/artillery-core/lib/runner.js:277:21
    at arrayMap (/Users/steph/.nvm/versions/node/v5.5.0/lib/node_modules/artillery/node_modules/artillery-core/node_modules/lodash/index.js:1406:25)
    at Function.map (/Users/steph/.nvm/versions/node/v5.5.0/lib/node_modules/artillery/node_modules/artillery-core/node_modules/lodash/index.js:6710:14)
    at runScenario (/Users/steph/.nvm/versions/node/v5.5.0/lib/node_modules/artillery/node_modules/artillery-core/lib/runner.js:274:27)
    at EventEmitter.<anonymous> (/Users/steph/.nvm/versions/node/v5.5.0/lib/node_modules/artillery/node_modules/artillery-core/lib/runner.js:155:5)
    at emitNone (events.js:80:13)
    at EventEmitter.emit (events.js:179:7)
```

**Comment by hassy** [comment]
Is this with the latest version of Artillery?

**Comment by carasel** [comment]
I believe so, installed it yesterday, version 1.4.1

**Comment by hassy** [comment]
You need v1.5 for socket.io :-) (`npm install -g artillery@latest`)

**Comment by carasel** [comment]
Cheers. Can't see that mentioned in the docs, would be good if it was on the testing socket.io page :)
