### ISSUE TITLE
Large body responses raise Invalid String length errors

### ISSUE THREAD

**Issue by wrightp** [shoreditch-ops/artillery#142]
The use case I'm validating is the performance of our infrastructure which uses a caching CDN. The test script calls a GET request to download a file. The virtual users download the appropriate file as binary data. This is fine, but once the phases are complete artillery raises an error:

```
          debugResponse(JSON.stringify(body, null, 2));
                             ^

RangeError: Invalid string length
    at Object.stringify (native)
    at Request.requestCallback [as _callback] (/usr/local/lib/node_modules/artillery/node_modules/artillery-core/lib/engine_http.js:198:30)
    at Request.self.callback (/usr/local/lib/node_modules/artillery/node_modules/request/request.js:200:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/artillery/node_modules/request/request.js:1067:10)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/artillery/node_modules/request/request.js:988:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
```

Note: during the `run` DEBUG is not enabled.

If I create a small set of virtual users and downloads I can get the scenario to pass. It seems to be more prevalent when there are several virtual users or perhaps very large file sizes.

I've tried commenting out the offending line to have artillery fail at the same time, but with this error:

```
 /buffer.js:500
    throw new Error('"toString()" failed');
    ^

Error: "toString()" failed
    at Buffer.toString (buffer.js:500:11)
    at BufferList.toString (/usr/local/lib/node_modules/artillery/node_modules/bl/bl.js:178:33)
    at Request.<anonymous> (/usr/local/lib/node_modules/artillery/node_modules/request/request.js:1042:32)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/artillery/node_modules/request/request.js:988:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:973:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
```

**Comment by hassy** [comment]
Thanks @wrightp. How large are these files? I'll try to replicate the error.

This looks like it might be a `request` issue. I have submitted a patch to `request` before to fix a bug where it would fail when dealing with large files - this could be related.

**Comment by wrightp** [comment]
The payload of urls I'm randomly loading from have file sizes ranging from 20 MB to 455 MB. I will pare this data set down to see if it's specific to file size.

**Comment by wrightp** [comment]
Update after some experimentation:
- Single virtual user downloading 1 20 MB file - success
- Single virtual user downloading 1 450 MB file produces error:
```
Error: "toString()" failed
    at Buffer.toString (buffer.js:500:11)
    at BufferList.toString (/usr/local/lib/node_modules/artillery/node_modules/bl/bl.js:178:33)
```
- Multiple virtual users downloading 450 MB files produces error:
```
RangeError: Invalid string length
    at Object.stringify (native)
    at Request.requestCallback [as _callback] (/usr/local/lib/node_modules/artillery/node_modules/artillery-core/lib/engine_http.js:198:30)
```

**Comment by hassy** [comment]
The problem was fixed a long while ago now but this issue never got closed. :)

**Comment by vanthome** [comment]
I have the same issue with the current version. In how far did this get solved?
