### ISSUE TITLE
Traceback when using loop in a websocket scenario

### ISSUE THREAD

**Issue by s0undt3ch** [shoreditch-ops/artillery#222]
Consider the following JSON definition:
```json
{
  "config": {
    "target": "ws://username:password@127.0.0.1:8080/ws",
    "phases": [
      { "duration": 10, "arrivalRate": 1 }
    ]
  },
  "scenarios": [
    {
      "engine": "ws",
      "flow": [
        {"loop": [
          {"send": "hello"}
        ], "count": 1000
        }
      ]
    }
  ]
}
```
When running the above I'm seeing:
```
Log file: artillery_report_20161206_175188.json

Phase 0 started - duration: 10s
 -TypeError: Cannot set property '$loopCount' of undefined
    at aLoop (/usr/lib/node_modules/artillery/node_modules/artillery-core/lib/engine_util.js:57:32)
    at fn (/usr/lib/node_modules/artillery/node_modules/async/lib/async.js:746:34)
    at /usr/lib/node_modules/artillery/node_modules/async/lib/async.js:1213:16
    at /usr/lib/node_modules/artillery/node_modules/async/lib/async.js:166:37
    at /usr/lib/node_modules/artillery/node_modules/async/lib/async.js:706:43
    at /usr/lib/node_modules/artillery/node_modules/async/lib/async.js:167:37
    at /usr/lib/node_modules/artillery/node_modules/async/lib/async.js:1209:30
    at WebSocket.<anonymous> (/usr/lib/node_modules/artillery/node_modules/artillery-core/lib/engine_ws.js:75:14)
    at emitNone (events.js:86:13)
    at WebSocket.emit (events.js:185:7)
 \^C
```

**Comment by hassy** [comment]
Thanks for the bug report s0undt3ch!

This has been fixed already (https://github.com/shoreditch-ops/artillery/issues/141). A new release will be published shortly with the fix.

**Comment by hassy** [comment]
@s0undt3ch `v1.5.0-18` out now - https://github.com/shoreditch-ops/artillery/releases/tag/1.5.0-18

**Comment by s0undt3ch** [comment]
Thanks! Confirmed that latest release works great!
