### ISSUE TITLE
Testing WS with 'loop': TypeError: Cannot read property 'ws' of undefined

### ISSUE THREAD

**Issue by igorclark** [shoreditch-ops/artillery#257]
Hi there, when I try to run a WS test using `loop`, I get this error intermittently. I *think* it might be related to there being an error on the socket - sometimes it seems to correspond - but I can't say for sure. Using a hard-coded set of `send` message entries equivalent to what the `loop` would generate, against the same endpoint and with nothing else changed, the error doesn't happen. `node v6.9.5`, OSX 10.11.6.

I'd love to be able to use `loop` to create longer and more complex scenarios. Any ideas what might be happening here?

Thanks!

```
$ artillery run test/load/conf/artillery.yaml
Log file: artillery_report_20170213_143955.json

Phase 0 started - duration: 30s

Report for the previous 10s @ 2017-02-13T13:39:53.603Z
  Scenarios launched:  412
  Scenarios completed: 367
  Requests completed:  29360
  Concurrent users:    47
  RPS sent: 3244.2
  Request latency:
    min: 0.1
    max: 58.3
    median: 0.4
    p95: 2.8
    p99: 5.9
  Scenario duration:
    min: 324.9
    max: 1279.8
    median: 582.6
    p95: 1062.5
    p99: 1216.3
  Codes:
    0: 29360
 |TypeError: Cannot read property 'ws' of undefined
    at scenarioWaterfallCb (/usr/local/lib/node_modules/artillery/node_modules/artillery-core/lib/engine_ws.js:115:20)
    at /usr/local/lib/node_modules/artillery/node_modules/async/lib/async.js:52:16
    at /usr/local/lib/node_modules/artillery/node_modules/async/lib/async.js:1209:30
    at /usr/local/lib/node_modules/artillery/node_modules/artillery-core/lib/engine_util.js:84:16
    at /usr/local/lib/node_modules/artillery/node_modules/async/lib/async.js:785:21
    at /usr/local/lib/node_modules/artillery/node_modules/async/lib/async.js:167:37
    at /usr/local/lib/node_modules/artillery/node_modules/artillery-core/lib/engine_util.js:80:18
    at /usr/local/lib/node_modules/artillery/node_modules/async/lib/async.js:52:16
    at /usr/local/lib/node_modules/artillery/node_modules/async/lib/async.js:696:30
    at /usr/local/lib/node_modules/artillery/node_modules/async/lib/async.js:167:37

Report for the previous 10s @ 2017-02-13T13:40:03.672Z
  Scenarios launched:  469
  Scenarios completed: 455
  Requests completed:  36400
  Concurrent users:    66
  RPS sent: 3226.95
  Request latency:
    min: 0.1
    max: 111.9
    median: 0.6
    p95: 2.9
    p99: 7.6
  Scenario duration:
    min: 594.9
    max: 5278.7
    median: 987.2
    p95: 1489.4
    p99: 2739.5
  Codes:
    0: 36400
```

**Comment by hassy** [comment]
Which version of Artillery is this? (`artillery -V`)

**Comment by igorclark** [comment]
Hi @hassy, thanks - I should have thought to check. It's the version that `npm` gave me by default, `1.5.0`.

**Comment by hassy** [comment]
Yes, from a quick glance through the source that looks like a bug. Thanks for taking the time to report it @igorclark

**Comment by hassy** [comment]
@igorclark try the new `v1.5.1`, that should fix the problem.

**Comment by igorclark** [comment]
Morning @hassy, yes, that works great. Thank you!
