### ISSUE TITLE
Error when creating the output file for a long running test

### ISSUE THREAD

**Issue by danula** [shoreditch-ops/artillery#373]
For a long-running test (12 hours in this particular case) artillery completes the tests but fails to produce the output into the specified JSON file.

```
All virtual users finished
Summary report @ 15:07:37(+0000) 2017-09-20
  Scenarios launched:  2160000
  Scenarios completed: 2160000
  Requests completed:  2160000
  Concurrent users:    6315
  RPS sent: 49.97
  Request latency:
    min: 1.7
    max: 1160.4
    median: 1.9
    p95: 3.4
    p99: 7.5
  Scenario duration:
    min: 2.2
    max: 1160.9
    median: 2.4
    p95: 5.1
    p99: 9.2
  Scenario counts:
    0: 2160000 (100%)
  Codes:
    204: 2160000

Log file: result1.json
/usr/lib/node_modules/artillery/lib/commands/run.js:96
            JSON.stringify(
                 ^

RangeError: Invalid string length
    at JSON.stringify (<anonymous>)
    at EventEmitter.<anonymous> (/usr/lib/node_modules/artillery/lib/commands/run.js:96:18)
    at emitOne (events.js:120:20)
    at EventEmitter.emit (events.js:210:7)
    at Runner._onWorkerMessage (/usr/lib/node_modules/artillery/lib/runner.js:229:19)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at emit (internal/child_process.js:774:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by hassy** [comment]
Thanks @danula. This is a known issue. We'll probably switch over to either line-delimited JSON or CSV as the output format in future.

**Comment by teebu** [comment]
Any update on this? While my test isn't running for that long, little less than 10 minutes, the output is not being created.

**Comment by karmseveeratjisc** [comment]
still seems to be an issue? we also have a short test but it does a lot of requests and are getting this error now
