### ISSUE TITLE
Testing socket.io application. "TypeError: Cannot read property 'createScenario' of undefined"

### ISSUE THREAD

**Issue by Hello-Zeze** [shoreditch-ops/artillery#422]
[simple_test.txt](https://github.com/shoreditch-ops/artillery/files/1675025/simple_test.txt)

Hi, I'm trying to run an artillery test for a socket.io appplication. node -v: 7.0.0 artillery -V:  1.6.0-12

Started phase 0, duration: 600s @ 21:58:18(+0200) 2018-01-29
⠹ TypeError: Cannot read property 'createScenario' of undefined
    at /usr/local/lib/node_modules/artillery/node_modules/artillery-core/lib/runner.js:347:24
    at arrayMap (/usr/local/lib/node_modules/artillery/node_modules/artillery-core/node_modules/lodash/lodash.js:574:23)
    at Function.map (/usr/local/lib/node_modules/artillery/node_modules/artillery-core/node_modules/lodash/lodash.js:8851:14)
    at runScenario (/usr/local/lib/node_modules/artillery/node_modules/artillery-core/lib/runner.js:342:36)
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/artillery/node_modules/artillery-core/lib/runner.js:252:5)
    at emitNone (events.js:86:13)
    at EventEmitter.emit (events.js:185:7)
    at UniformProcess.<anonymous> (/usr/local/lib/node_modules/artillery/node_modules/artillery-core/lib/phases.js:181:10)
    at emitNone (events.js:86:13)
    at UniformProcess.emit (events.js:185:7)
Unexpected error, Artillery shutting down.

**Comment by hassy** [comment]
engine should be `socketio`, not 'socket.io`

**Comment by rajeet** [comment]
---
config:
  target: https://socket.foodmandu.com
  phases:
    - duration: 5
      arrivalRate: 1
  engine: 
    socketio-v2: 
      path: "/driver"
      query: "uid=132&key=danV9yPzEvTsesz8m1ik5PAUBs2SsR36drVWYSpfl74ynDN9vvrsoRzgdLU7U"
scenarios:
  - name: First Scenario
    engine: socketio-v2
    flow:
      - emit:
          channel: data
      - response:
          channel: data


<img width="974" alt="Screenshot 2022-11-19 at 12 19 06" src="https://user-images.githubusercontent.com/6507257/202838004-a9ce153f-9bea-41f8-b04e-349cae7fac84.png">

Hello, Here I have same issue with undefined (reading 'createScenario')
