### ISSUE TITLE
artillery quick bug

### ISSUE THREAD

**Issue by tomgco** [shoreditch-ops/artillery#472]
Expected: When running `artillery quick` without any arguments, you would expect to see a help menu. 
Actual:

```sh
$ artillery quick
/usr/lib/node_modules/artillery/lib/commands/quick.js:45
  var rate = options.r || options.rate;
                     ^

TypeError: Cannot read property 'r' of undefined
    at Command.quick (/usr/lib/node_modules/artillery/lib/commands/quick.js:45:22)
    at Command.listener (/usr/lib/node_modules/artillery/node_modules/commander/index.js:301:8)
    at Command.emit (events.js:182:13)
    at Command.parseArgs (/usr/lib/node_modules/artillery/node_modules/commander/index.js:615:12)
    at Command.parse (/usr/lib/node_modules/artillery/node_modules/commander/index.js:458:21)
    at Object.<anonymous> (/usr/lib/node_modules/artillery/bin/artillery:52:9)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
```

Version:

```
$ artillery --version
1.6.0-17
```

**Comment by hassy** [comment]
Thanks! :D
