### ISSUE TITLE
How to write my own engine? Docs?

### ISSUE THREAD

**Issue by rvetere** [shoreditch-ops/artillery#508]
Hi i found the repository "https://github.com/shoreditch-ops/artillery-engine-kinesis" which seems to solve exactly what i need - writing my own engine.. I did it already by forking the whole artillery repository and got it running, but it feels as a total overkill to fork the whole thing just to introduce a new engine.

But when i see code like this:

```
      let runnerEngines = _.map(
      Object.assign({}, Engines, runnableScript.config.engines),
      function loadEngine(engineConfig, engineName) {
        let moduleName = 'artillery-engine-' + engineName;
        try {
          if (Engines[engineName]) {
            moduleName = './engine_' + engineName;
          }
          let Engine = require(moduleName);
     ....
```

-> the runner code is hardcoded looking into his own folder relatively with all the entries of "Engines"... i don't see how this should be dynamically able to pick up some new written engines at all oO

So... how should this work?

**Comment by hassy** [comment]
hi @rvetere, the way to get it going locally is:

1. Clone Artillery, run `npm install` in the directory, this will let you run a local copy of Artillery with `./bin/artillery`
2. In the directory where your custom engine code is (let's say `artillery-engine-rvetere`) run `npm link`
3. Back inside Artillery's source dir run `npm link artillery-engine-rvetere` (more info on [npm link](https://docs.npmjs.com/cli/link))

This will allow that copy of Artillery to find and load your custom engine. It's important that you set the engine field of your scenario:

```yaml
config:
  target: "some.target"
scenarios:
  - name: "Custom engine scenario"
    engine: "rvetere"
    flow:
     - do: something
     - do: something else
```

**Comment by kraenhansen** [comment]
Another way to do this is to create a package that has a dependency on both artillery and your custom engine (could be installed from `./artillery-engine-custom`), this way artillery core will be able to require in your custom engine correctly.

**Comment by dtrunk90** [comment]
Both ways don't work for me:
```
> artillery run "test.yml"

Started phase 0 (Test Phase), duration: 10s @ 17:16:19(+0200) 2021-05-03
  . /usr/local/lib/node_modules/artillery/core/lib/runner.js:390
          return engine.createScenario(scenarioSpec, runState.scenarioEvents);
                        ^

TypeError: Cannot read property 'createScenario' of undefined
    at /usr/local/lib/node_modules/artillery/core/lib/runner.js:390:25
    at arrayMap (/usr/local/lib/node_modules/artillery/node_modules/lodash/lodash.js:653:23)
    at Function.map (/usr/local/lib/node_modules/artillery/node_modules/lodash/lodash.js:9622:14)
    at runScenario (/usr/local/lib/node_modules/artillery/core/lib/runner.js:385:36)
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/artillery/core/lib/runner.js:274:7)
    at EventEmitter.emit (events.js:315:20)
    at UniformProcess.<anonymous> (/usr/local/lib/node_modules/artillery/core/lib/phases.js:182:10)
    at UniformProcess.emit (events.js:315:20)
    at /usr/local/lib/node_modules/artillery/node_modules/arrivals/lib/index.js:47:10
    at NanoTimer.setInterval (/usr/local/lib/node_modules/artillery/node_modules/arrivals/node_modules/nanotimer/lib/nanotimer.js:220:5)
```

**Comment by hassy** [comment]
Does your engine define a `createScenario` function @dtrunk90?

**Comment by dtrunk90** [comment]
@hassy the engine itself is undefined, not the createScenario function.

**Comment by hassy** [comment]
ah yes, sorry! does Artillery print a warning that it can't load the engine when you run the test? a minimal reproducible example would be great.

**Comment by dtrunk90** [comment]
https://github.com/dtrunk90/artillery-engine-rsocket

**Comment by hassy** [comment]
Ah sorry, the engine needs to be specified in `config.engines` like this:

```
config:
  target: localhost
  phases:
    - duration: 10
      arrivalRate: 1
      name: "Test Phase"
  engines:
    rsocket: {}
```

I was able to run your script + engine after adding that bit to the config. Let me know if you run into any other issues!

**Comment by dtrunk90** [comment]
At least it runs. It doesn't send any requests but that could be a problem of my custom engine implementation.

**Comment by hassy** [comment]
Great! Feel free to create a new RSocket-specific issue if you need pointers @dtrunk90

**Comment by dtrunk90** [comment]
Thank you.
