### ISSUE TITLE
On windows quick mode fails if c:\tmp folder doesn't exists

### ISSUE THREAD

**Issue by rzio** [shoreditch-ops/artillery#61]
I've edited the call stack a bit to remove personal info

```
artillery quick --duration 10 --rate 20 https://example.com
fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'C:\tmp\artillery_quick_script_20160302_223210.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.writeFileSync (fs.js:1155:15)
    at Command.quick (<user_home>\AppData\Roaming\npm\node_modules\artillery\lib\commands\quick.js:79:6)
    at Command.listener (<user_home>\AppData\Roaming\npm\node_modules\artillery\node_modules\commander\index.js:301:8)
    at emitTwo (events.js:87:13)
    at Command.emit (events.js:172:7)
    at Command.parseArgs (<user_home>\AppData\Roaming\npm\node_modules\artillery\node_modules\commander\index.js:615:12)
    at Command.parse (<user_home>\AppData\Roaming\npm\node_modules\artillery\node_modules\commander\index.js:458:21)
    at Object.<anonymous> (<user_home>\AppData\Roaming\npm\node_modules\artillery\bin\artillery:58:9)
```

**Comment by hassy** [comment]
Thanks for reporting this bug. The fix would be to use the [`tmp`](https://www.npmjs.com/package/tmp) package instead of hardcoding `/tmp` if you want to take a stab at it. :) Otherwise, I'll patch it soon.

**Comment by hassy** [comment]
Fixed in `artillery 1.3.8`, thanks for reporting the bug @rzio

**Comment by megh0682** [comment]
Hello, I am trying to flush the output of quick test to a json file on computer as below but it gives me an error.  without -o option it is working fine  

C:\Users\meiyer>artillery quick -d 30 -r 5 -n 20 -o `C:\Users\meiyer\artillery_r
eport_20160809_092466.json' http://127.0.0.1:8888/start
C:\Users\meiyer\AppData\Roaming\npm\node_modules\artillery\lib\commands\quick.js
:82
  } else if (p.protocol.match(/http/)) {
                       ^

TypeError: Cannot read property 'match' of null
    at Command.quick (C:\Users\meiyer\AppData\Roaming\npm\node_modules\artillery
\lib\commands\quick.js:82:24)
    at Command.listener (C:\Users\meiyer\AppData\Roaming\npm\node_modules\artill
ery\node_modules\commander\index.js:301:8)
    at emitTwo (events.js:87:13)
    at Command.emit (events.js:172:7)
    at Command.parseArgs (C:\Users\meiyer\AppData\Roaming\npm\node_modules\artil
lery\node_modules\commander\index.js:615:12)
    at Command.parse (C:\Users\meiyer\AppData\Roaming\npm\node_modules\artillery
\node_modules\commander\index.js:458:21)
    at Object.<anonymous> (C:\Users\meiyer\AppData\Roaming\npm\node_modules\arti
llery\bin\artillery:61:9)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)

**Comment by hassy** [comment]
What version of Aritllery are you running @megh0682? There's a line-break in the command that you posted - I assume it's a copy-paste accident, but just want to double check.
